In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
import tensorflow

In [4]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation= 'linear'))

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.get_weights()

[array([[-0.8768333, -0.2663992],
        [ 1.2141589, -1.0943927]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.55200166],
        [ 0.3216927 ]], dtype=float32),
 array([0.], dtype=float32)]

In [17]:
new_weights = [np.array([[0.1, 0.1],
        [ 0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [ 0.1 ]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [18]:
model.set_weights(new_weights)

In [20]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)

In [22]:
model.compile(loss = 'mean_squared_error', optimizer=optimizer)

In [23]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 7ms/step - loss: 27.8838
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5572
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 27.2599
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.8942
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 26.5474
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 26.1777
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8187
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4332
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0696
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6296
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2150
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 23.8054
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [24]:
model.get_weights()

[array([[0.37374517, 0.37374517],
        [0.3658955 , 0.3658955 ]], dtype=float32),
 array([0.27254042, 0.27254042], dtype=float32),
 array([[0.37315136],
        [0.37315136]], dtype=float32),
 array([0.20500515], dtype=float32)]